apiVersion: apps/v1
kind: Deployment
metadata:
  name: lmstudio-mcp
  labels:
    app: lmstudio-mcp
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lmstudio-mcp
  template:
    metadata:
      labels:
        app: lmstudio-mcp
        version: v1
    spec:
      hostNetwork: true  # Required for LM Studio access on localhost
      containers:
      - name: lmstudio-mcp
        image: ghcr.io/infinitimeless/lmstudio-mcp:latest
        env:
        - name: LMSTUDIO_API_BASE
          value: "http://localhost:1234/v1"
        stdin: true
        tty: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import lmstudio_bridge; print('OK')"
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import lmstudio_bridge; print('OK')"
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lmstudio-mcp-service
  labels:
    app: lmstudio-mcp
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: lmstudio-mcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lmstudio-mcp-config
  labels:
    app: lmstudio-mcp
data:
  LMSTUDIO_API_BASE: "http://localhost:1234/v1"
  LOG_LEVEL: "INFO"
  TIMEOUT: "30"
